# Generated by Django 3.1.2 on 2020-12-09 12:23

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('union_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='union_photo')),
                ('union_name', models.TextField(max_length=500)),
                ('union_location', models.CharField(blank=True, max_length=60)),
                ('union_members', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('union_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_text', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('studentunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='union.studentunion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('service_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Security', 'Security'), ('Acc', 'Acc')], max_length=60)),
                ('location', models.CharField(blank=True, max_length=60)),
                ('contact', models.CharField(blank=True, max_length=60)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('studentunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='union.studentunion')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_name', models.TextField(max_length=120)),
                ('bs_description', models.TextField(blank=True)),
                ('bs_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='bs_photo')),
                ('bs_email', models.EmailField(max_length=254)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('studentunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='union.studentunion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
